### ISSUE TITLE
Can you share your oral slides

### ISSUE THREAD

**Issue by qijiezhao** [psmmettes/spatial-aware-object-embeddings#1]
Hi, Mettes:

I am very interested in your work, and I plan to have a review of your paper with my group, can you please generously have a sharing of your slides? thank you.

**Comment by psmmettes** [comment]
Hi,

Great to hear of your interest. I have a sharable link to the slides here: https://docs.google.com/presentation/d/1HmbxjrRIPYzn3hbbzCwiJtl28ub7X35rRNGh-zFfGj4/edit?usp=sharing

Note that the slides are at a high level of abstraction for the sake of the ICCV talk, so a lot of details are left out.

Good luck!
- Pascal
